version: "3.9"

services:
  app:
    build: .
    container_name: materias_service
    restart: always
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://3.80.235.23:27017/materiasdb
