version: "3.9"
services:
  app:
    build: .
    container_name: materias_service
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://mongo:27017/materiasdb

